annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: K10
  catalog.cattle.io/release-name: k10
apiVersion: v2
appVersion: 4.5.14
description: Kastenâ€™s K10 Data Management Platform
home: https://kasten.io/
icon: http://k10docs.aws.kasten.io.s3-website-us-west-1.amazonaws.com/latest/_static/logo-kasten-k10-blue-white.png
kubeVersion: '>= 1.17.0-0'
maintainers:
- email: support@kasten.io
  name: kastenIO
name: k10
version: 4.5.1400
